# Generated by Django 4.0.6 on 2022-07-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rentdetails',
        ),
    ]
