# Generated by Django 4.0.6 on 2022-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0002_delete_rentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
                ('laddress', models.CharField(max_length=80)),
                ('anumber', models.CharField(max_length=12)),
                ('pnumber', models.CharField(max_length=10)),
                ('pdetails', models.CharField(max_length=50)),
                ('ramt', models.CharField(max_length=6)),
                ('damt', models.CharField(max_length=6)),
                ('sdate', models.DateField()),
                ('ldate', models.DateField()),
            ],
        ),
    ]
