# Generated by Django 4.0.6 on 2022-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
