# Generated by Django 4.0.6 on 2022-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_rentdetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ramt', models.CharField(max_length=7)),
                ('rmonth', models.CharField(max_length=10)),
                ('rdate', models.DateField()),
            ],
        ),
    ]
