# Generated by Django 2.1.15 on 2022-12-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdetails',
            name='anumber',
        ),
        migrations.RemoveField(
            model_name='rentdetails',
            name='pnumber',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
