# Generated by Django 2.1.15 on 2022-12-07 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mdate',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 13, 19, 27, 610165, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
