# Generated by Django 2.1.15 on 2022-12-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_message_mdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='rdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='rmonth',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
