# Generated by Django 2.0.2 on 2022-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20221207_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=2, max_length=254, upload_to=None),
            preserve_default=False,
        ),
    ]
