# Generated by Django 2.0.2 on 2022-12-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
